### ISSUE TITLE
テストがfailではなくerrorした場合の処理がない

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg#286]
Math70がそんな例．
テスト自体がヌルポを吐くので，failではなくerrorである．

これFLどうなんの？

[genprogらは修正できる](https://github.com/Spirals-Team/defects4j-repair/blob/master/results/2015-august/Math/70/Genprog/results.json)らしい．

Math70のテストレポート
```
-------------------------------------------------------------------------------
Test set: org.apache.commons.math.analysis.solvers.BisectionSolverTest
-------------------------------------------------------------------------------
Tests run: 12, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.087 sec <<< FAILURE!
testMath369(org.apache.commons.math.analysis.solvers.BisectionSolverTest)  Time elapsed: 0.005 sec  <<< ERROR!
java.lang.NullPointerException
	at org.apache.commons.math.analysis.solvers.BisectionSolver.solve(BisectionSolver.java:88)
	at org.apache.commons.math.analysis.solvers.BisectionSolver.solve(BisectionSolver.java:66)
	at org.apache.commons.math.analysis.solvers.BisectionSolver.solve(BisectionSolver.java:72)
	at org.apache.commons.math.analysis.solvers.BisectionSolverTest.testMath369(BisectionSolverTest.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:232)
	at junit.framework.TestSuite.run(TestSuite.java:227)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:81)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:59)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.executeTestSet(AbstractDirectoryTestSuite.java:115)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.execute(AbstractDirectoryTestSuite.java:102)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:180)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:350)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:1021)
```

**Comment by shinsuke-mat** [comment]
```java
	@Rule
	public final Timeout globalTimeout = Timeout.seconds(10);
```
