### ISSUE TITLE
failするテストが成功扱いになっている

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg#288]
Math73が題材．
失敗テストが存在しないことになってしまって，当然FL無理，バグ直らない．

mvnではテストが失敗する（当然Defects4jにもそのテストがfailと明記されている）
```sh
$ mvn -Dtest=org.apache.commons.math.analysis.solvers.BrentSolverTest test
...
[INFO] Surefire report directory: C:\pbl\workspace\kGenProg\example\Math73\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.apache.commons.math.analysis.solvers.BrentSolverTest
Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.1 sec <<< FAILURE!

Results :

Failed tests:
  testBadEndpoints(org.apache.commons.math.analysis.solvers.BrentSolverTest)

Tests run: 6, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.280 s
[INFO] Finished at: 2018-08-31T20:30:28+09:00
[INFO] ------------------------------------------------------------------------
```

上記のテストレポート
```
-------------------------------------------------------------------------------
Test set: org.apache.commons.math.analysis.solvers.BrentSolverTest
-------------------------------------------------------------------------------
Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.104 sec <<< FAILURE!
testBadEndpoints(org.apache.commons.math.analysis.solvers.BrentSolverTest)  Time elapsed: 0.022 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Expecting IllegalArgumentException - non-bracketing
	at junit.framework.Assert.fail(Assert.java:47)
	at org.apache.commons.math.analysis.solvers.BrentSolverTest.testBadEndpoints(BrentSolverTest.java:334)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

failするテストの中身
```java
    public void testBadEndpoints() throws Exception {
      ...
        try {  // no bracket
            solver.solve(f, 1, 1.5, 1.2);
            fail("Expecting IllegalArgumentException - non-bracketing");
        } catch (IllegalArgumentException ex) {
            // expected
        }
    }
```

KGPでのJUnitの結果
```json
org.apache.commons.math.analysis.solvers.BrentSolverTest.testBadEndpoints={
  "executedTestFQN": "org.apache.commons.math.analysis.solvers.BrentSolverTest.testBadEndpoints",
  "wasFailed": false,
  "coverages": [
    //
  ]
}
```

**Comment by shinsuke-mat** [comment]
### バグ再現方法
アノテーションではなく継承ベースのテスト例題を作ればOK．
