### ISSUE TITLE
メモリを使いすぎて死ぬ

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg#299]
```
2018-09-05 23:38:36 [main] [DEBUG] jp.kusumotolab.kgenprog.ga.DefaultCodeValidation - enter exec(Gene, TargetProject)
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
```

Math73の2世代目後半で発生する．
ガバメモリ実装が原因．

基本的にオンメモリでの全Variantの記録は非現実的，というか不可能．

**Comment by shinsuke-mat** [comment]
このバグはかなりの割合で発生している
math1～80に対して7回（1割弱）発生している（乱数は1）．

math10，37，46，47は乱数1～9全てで再現している．
特定の題材で再現していることから，
おそらくkgpがメモリを食い尽くすというより，題材側でメモリリークしている気がする．

よって課題はこう
「題材側でメモリリークした場合にkgpが巻き込まれないようにできないか」

**Comment by shinsuke-mat** [comment]
メモリリークの様子．

```shell
$ less kgp-math047-1.result
...
org.apache.commons.math.complex.ComplexTest: Java heap space            # ★こいつが諸悪の根源
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.HashMap.newNode(HashMap.java:1747)
        at java.util.HashMap.putVal(HashMap.java:631)
        at java.util.HashMap.put(HashMap.java:612)
        at java.util.ListResourceBundle.loadLookup(ListResourceBundle.java:204)
        at java.util.ListResourceBundle.handleGetObject(ListResourceBundle.java:130)
        at java.util.ResourceBundle.getObject(ResourceBundle.java:441)
        at java.util.ResourceBundle.getString(ResourceBundle.java:407)
        at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:190)
        at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:141)
        at com.sun.tools.javac.util.JavacMessages.getLocalizedString(JavacMessages.java:135)
        at com.sun.tools.javac.util.Log.localize(Log.java:684)
        at com.sun.tools.javac.util.Log.printLines(Log.java:497)
        at com.sun.tools.javac.main.Main.resourceMessage(Main.java:610)
        at com.sun.tools.javac.main.Main.compile(Main.java:543)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at jp.kusumotolab.kgenprog.project.build.ProjectBuilder.build(ProjectBuilder.java:82)  # ★巻き込まれ
        at jp.kusumotolab.kgenprog.project.build.ProjectBuilder.build(ProjectBuilder.java:56)
        at jp.kusumotolab.kgenprog.project.test.TestExecutor.exec(TestExecutor.java:27)
        at jp.kusumotolab.kgenprog.Strategies.execTestExecutor(Strategies.java:52)
        at jp.kusumotolab.kgenprog.ga.VariantStore.createVariant(VariantStore.java:151)
        at jp.kusumotolab.kgenprog.ga.VariantStore.createVariant(VariantStore.java:56)
        at jp.kusumotolab.kgenprog.ga.RandomMutation.exec(RandomMutation.java:55)
        at jp.kusumotolab.kgenprog.KGenProgMain.run(KGenProgMain.java:81)
        at jp.kusumotolab.kgenprog.CUILauncher.launch(CUILauncher.java:49)
        at jp.kusumotolab.kgenprog.CUILauncher.main(CUILauncher.java:27)

real    12m38.990s
user    12m37.727s
sys     0m1.191s
```

スタックトレースを見るとkgpの`ProjectBuilder#build`が怪しそうだが，
スタックトレースの直前に題材側のテスト実行で `Java heap space` が出ている．

題材でmemリーク → kgpが巻き込まれてOutOfMemoryError → 死

**Comment by YoshikiHigo** [comment]
プロセスを切る以外の選択肢があまりない．
実装は大変．クラスタ化の実装で解決できるはず．

**Comment by hnymA** [comment]
ref #579
