### ISSUE TITLE
InsertOperationでClassCastExceptionが発生する．

### ISSUE THREAD

**Issue by YoshikiHigo** [kusumotolab/kGenProg#410]
### 実行環境
```sh
[higo@10:53] uname -a
Darwin higo-MacBookPro2018.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64
[higo@10:59] java -version
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)
```

### 例外を発生させるためのkgenprog.toml（CloseToZero01）の変更箇所
```sh
iff --git a/example/CloseToZero01/kgenprog.toml b/example/CloseToZero01/kgenprog.toml
index 3f84c99..7ad7a77 100644
--- a/example/CloseToZero01/kgenprog.toml
+++ b/example/CloseToZero01/kgenprog.toml
@@ -47,7 +47,7 @@ log-level = "TRACE"
 #test-time-limit = <sec>

 # Terminates searching solutions when the specified number of solutions are found.
-#required-solutions = <num>
+required-solutions = 10

 # Specifies random seed used by random number generator.
 #random-seed = <num>
```

### 発生した例外のスタックトレース
```sh
2018-11-14 10:53:32 [main] [DEBUG] JDTOperation - Opperation failed: org.eclipse.jdt.core.dom.ChildPropertyDescriptor cannot be cast to org.eclipse.jdt.core.dom.ChildListPropertyDescriptor
2018-11-14 10:53:32 [main] [TRACE] JDTOperation - Trace:
java.lang.ClassCastException: org.eclipse.jdt.core.dom.ChildPropertyDescriptor cannot be cast to org.eclipse.jdt.core.dom.ChildListPropertyDescriptor
	at jp.kusumotolab.kgenprog.project.jdt.InsertOperation.applyToASTRewrite(InsertOperation.java:22)
	at jp.kusumotolab.kgenprog.project.jdt.JDTOperation.applyEachAST(JDTOperation.java:51)
	at jp.kusumotolab.kgenprog.project.jdt.JDTOperation.lambda$0(JDTOperation.java:30)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at jp.kusumotolab.kgenprog.project.jdt.JDTOperation.apply(JDTOperation.java:31)
	at jp.kusumotolab.kgenprog.ga.DefaultSourceCodeGeneration.exec(DefaultSourceCodeGeneration.java:25)
	at jp.kusumotolab.kgenprog.Strategies.execSourceCodeGeneration(Strategies.java:48)
	at jp.kusumotolab.kgenprog.ga.VariantStore.createVariant(VariantStore.java:53)
	at jp.kusumotolab.kgenprog.ga.RandomMutation.exec(RandomMutation.java:50)
	at jp.kusumotolab.kgenprog.KGenProgMain.run(KGenProgMain.java:73)
	at jp.kusumotolab.kgenprog.CUILauncher.launch(CUILauncher.java:49)
	at jp.kusumotolab.kgenprog.CUILauncher.main(CUILauncher.java:27)
```

**Comment by a3636tako** [comment]
例外の起きている処理は
以下のプログラム
```java   
if (n == 0) {
  n++; // bug here
} else if (n > 0) {
  n--;
} else {
  n++;
}
```
のif blook
```java
{
  n++; // bug here
} 
```
のあとに
```java
return n;
```
を挿入する操作を行おうとしています

しかし、
```java   
if (n == 0) {
  n++; // bug here
} 
return n;
else if (n > 0) {
  n--;
} else {
  n++;
}
```
のようなプログラムを生成することはできないため、例外が発生しています。
考えられる解決策は以下のとおりです。

## 案1：何もしない
logレベルがdebugとなっているように、正しくないOperationによってある程度例外が発生するのは仕方ないと考えています。
GenerationFaiedSourceCodeがreturnされるため、実行継続には問題ありません。

## 案2：InsertOperationの対象を絞る。
現状のInsertOperationで正しい操作となりうるのは、挿入先の親がBlockであるときだけだと思われます。
RandomMutaionで挿入先を選択する際にチェックすることで、正しくないInsertOperationを生成させなくできると思われます。

**Comment by YoshikiHigo** [comment]
案2の方がよいと思ったんですが，案1と案2だと実行速度に差はでてきますか？

**Comment by a3636tako** [comment]
案2の方が多少高速になると考えられますが、時間かかる処理は例外発生箇所のあとなので、大きな違いにはならないと思います。

@mtj0928 実装よろしくお願いします。

**Comment by shinsuke-mat** [comment]
【2018/11/15 議論】

AとBを別のストラテジと捉えたほうが良い．
そうしておくと比較もできる．

A: `RandomMutation`
B: `SyntaxValidMutation`
