### ISSUE TITLE
KGPの実行結果に再現性がない

### ISSUE THREAD

**Issue by ty-v1** [kusumotolab/kGenProg#436]
## 問題
起動する環境・方法によって、生成されるVariantが異なる。
そのため、KGenProgMainテストが失敗したり成功したりする。   

## CloseToZero03の実験結果
* Windows + Eclipse + テストを実行 : 3世代目で例外発生

* Windows + Eclipse + テストをデバッグ実行 
  * 成功時 : 15世代目で成功
  * 例外発生時 : 19世代目で失敗

* Mac + Intellij + テストを実行 : 8世代目で例外発生

* Mac + Intellij + テストをデバッグ実行
  * 成功時 : 42世代目でテストが成功
  * 例外発生時 : 25世代目でテストが失敗

* Mac + Intellij + テストと同じ条件で実行 : 4・6・７世代目で成功

* Mac + Intellij + テストと同じ条件でデバッグ実行 : 3世代目で例外発生

発生する例外はNoSuchElementException
```
java.util.NoSuchElementException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1444)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1476)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1474)
	at java.util.Collections.max(Collections.java:708)
	at jp.kusumotolab.kgenprog.KGenProgMain.getMaxText(KGenProgMain.java:206)
	at jp.kusumotolab.kgenprog.KGenProgMain.logGenerationSummary(KGenProgMain.java:187)
	at jp.kusumotolab.kgenprog.KGenProgMain.run(KGenProgMain.java:107)
	at jp.kusumotolab.kgenprog.KGenProgMainTest.testCloseToZero03(KGenProgMainTest.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by shinsuke-mat** [comment]
話を切り分けよう．

### A. 例外の中身
#437 によるもの．
その世代でビルド成功バリアントが一つも生まれなかった場合に発生する．

この問題自体は本ISSUEにはあまり関係ないので，スルーでOK．
本ISSUEの本質は以下の乱数再現の部分．

### B. 同一環境で乱数が再現しない
そもそも同一環境で乱数再現性の問題が発生するかどうかが重要．
何度か試したが，きちんと乱数は再現されているように見える．

```shell
$ git co master
$ gradle assemble
$ bin=$(realpath build/libs/kGenProg.jar)
$ bin=$(cygpath -w $bin)  # win環境用のパッチ
$ (cd example/CloseToZero03; \
  java -jar $bin -r . \
  -s src/example/CloseToZero.java \
  -t src/example/CloseToZeroTest.java)
# 何度実行しても成功発見できず．

$ (cd example/CloseToZero03; \
  java -jar $bin -r . \
  -s src/example/CloseToZero.java \
  -t src/example/CloseToZeroTest.java \
  --random-seed=7)
# 何度実行しても7代目で成功．
```

### C. 別環境で乱数が再現しない
軽く試したところ，確かに別環境だと乱数再現しないようにみえる．
が，いったん後回し．
B解決後に考えるべき．

### D. `-v` をつけると結果が変わる
A～C整理中に発見した別の問題（？）．
忘れないようにメモ．

```shell
$ (cd example/CloseToZero03; \
  java -jar $bin -r . \
  -s src/example/CloseToZero.java \
  -t src/example/CloseToZeroTest.java \
  --random-seed=7)
# 何度実行しても7代目で成功．

$ (cd example/CloseToZero03; \
  java -jar $bin -r . \
  -s src/example/CloseToZero.java \
  -t src/example/CloseToZeroTest.java \
  --random-seed=7 \
  -v)
# 何度実行しても成功発見できず．
```

**Comment by ty-v1** [comment]
乱数は同じ

普通に実行
```
1世代目
----------------------------------------------------------------
Elapsed time: 0 seconds
Variants: generated 10, syntax-valid 8, build-succeeded 4
Fitness: max 0.75(3), min 0.5(1), ave 0.6875
----------------------------------------------------------------

デバッグ実行
```
1世代目
----------------------------------------------------------------
Elapsed time: 0 seconds
Variants: generated 10, syntax-valid 8, build-succeeded 5
Fitness: max 0.75(3), min 0.25(2), ave 0.55
----------------------------------------------------------------
```

**Comment by ty-v1** [comment]
上の起動構成
```
# Specifies the path to the root directory of the target project.
root-dir = "./"

# Specifies paths to "product" source code (i.e. main, non-test code),
# or to directories containing them.
src = ["src/example/CloseToZero.java"]

# Specifies paths to test source code, or to directories containing them.
test = ["src/example/CloseToZeroTest.java"]

# Specifies class paths needed to build the target project.
#cp = [<class-path>, ...]

# Specifies fully qualified names of test classes executed during evaluation
# of variants (i.e. fix-candidates).
# By default, all tests are executed. It might take a terribly long time,
# so we recommend you specify test classes detecting a bug.
#exec-test = [<fqn>, ...]

# Specifies the path to working directory. By default, a working directory is
# created under system temporary directory (i.e. $TMPDIR on *nix, %TMP% on Windows)
# every kGenProg execution.
working-dir = "tmp/work"

# Writes patches kGenProg generated to the specified directory.
#out-dir = <path>

# Selects the log level to be shown at least.
# Acceptable values are "OFF", "ERROR", "WARN", "INFO", "DEBUG", "TRACE", or "ALL"
log-level = "DEBUG"

# Specifies how many variants are generated in a generation by a mutation.
#mutation-generating-count = <num>

# Specifies how many variants are generated in a generation by a crossover.
#crossover-generating-count = <num>

# Specifies how many variants survive in a generation.
#headcount = <num>

# Terminates searching solutions when the specified number of generations reached.
max-generation = 100

# Terminates searching solutions when the specified time has passed.
time-limit = 600

# Specifies time limit to build and test for each variant in second
test-time-limit = 1

# Terminates searching solutions when the specified number of solutions are found.
required-solutions = 1

# Specifies random seed used by random number generator.
random-seed = 2
```

**Comment by shinsuke-mat** [comment]
### C. 別環境で乱数が再現しない
上の続き

まwin  vs ひmac で上記のjar実行比較したところ，
やはり別環境だと結果が異なる．

ただし同一環境での結果（B）は何度実行しても全く同じ．
そういう仕様か？

### D. -v をつけると結果が変わる
肥後環境でも再現．
致命的な問題．

### 一旦まとめ
A. 無視
B. 問題なし
C. 問題あるかも（別環境では結果が異なる．調査が必要）
D. 問題あり（-vつけると結果が異なる）

**Comment by shinsuke-mat** [comment]
@mtj0928

### Dの調査結果
半分くらい理解した．
少なくとも一つのバグ箇所を発見．
乱数の消費ではなく，もっと深淵な問題．

この部分．
https://github.com/kusumotolab/kGenProg/blob/0570106853b795f4642d07e00c2fcc82a9b4b4c8/src/main/java/jp/kusumotolab/kgenprog/ga/StatementSelection.java#L75-L76

ここでルーレット選択の母集団 `candidates` をMapから取り出しているが，
この `candidates` の順序が実行の仕方（パラメタの有無）で変わる模様．
（理由はしらん．Mapだからそんなもん？）

結果的に，以下 `Roulette` クラスのこの部分に順序が保証されないリスト `separateList` が飛んでくる．
https://github.com/kusumotolab/kGenProg/blob/0570106853b795f4642d07e00c2fcc82a9b4b4c8/src/main/java/jp/kusumotolab/kgenprog/ga/Roulette.java#L26-L30

変数 `total` は積算値なので，順序が変わるとリストの値が変わる．

結論：リストをソートしておけば上記バグは直る．

### 残る問題
最初に「半分」と書いた理由は以下2点．
- D1. そもそも，なぜ実行の仕方（特にパラメタ指定の有無）でMapの順序が変わるのか？
- D2. 上記バグを修正しても，まだシード固定時の再現性が保証されない．別の部分にも似たバグありそう．

**Comment by a3636tako** [comment]
HashMultiMapは重複した要素をSetで持つMultiMapのようです。
ArrayListMultimapを使うと解決するかもしれません
https://google.github.io/guava/releases/19.0/api/docs/com/google/common/collect/ArrayListMultimap.html
