### ISSUE TITLE
CLI オプションの妥当性確認が不十分

### ISSUE THREAD

**Issue by a-tanikd** [kusumotolab/kGenProg#461]
#459 で Path の存在確認は行ったが，その他にも確認すべき項目が多数ある．

### srcとtestが重複しているケース
```
src = ["src/example/"]
test = ["src/example/"]
```

JDTの例外．当然利用者には意味不明．
そもそもsrc/testの重複を許すのかという議論が必要．
```
$ java -jar $x --config kgenprog.toml
Exception in thread "main" java.lang.IllegalStateException: Duplicate key jp.kusumotolab.kgenprog.project.jdt.GeneratedJDTAST@397fbdb
        at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
```
### toml内で行末に余計なスペースがあるケース
```
max-generation = 99 
                   ↑ ここにスペース
```

"Invalid value: " というエラーが出る．かなり不親切なエラーメッセージ
```
$ java -jar $x --config kgenprog.toml
Exception in thread "main" com.electronwill.nightconfig.core.io.ParsingException: Invalid value: 99
        at com.electronwill.nightconfig.core.io.Utils.parseLong(Utils.java:67)
```

### 型が正しくないケース
```
max-generation = "99"
```

エラー無しでusageがおもむろに出力
```
$ java -jar $x --config kgenprog.toml
 --config <path>                    : Specifies the path to the config file.
 --crossover-generating-count <num> : Specifies how many variants are generated
```

### 正数を期待するパラメタに負数や小数点を与えるケース
```
max-generation = -9
```
```
max-generation = 99.9
```

普通に動いてしまう．エラー出るべき．
```
$ java -jar $x --config kgenprog.toml
2018-12-13 14:14:57 [main] [INFO]  KGenProgMain -
==================== kGenProg Configuration ====================
targetProject =
executionTests = []
```

### 特定の文字列を期待するパラメタに期待外の文字列を与えるケース
```
log-level = "TRACEE"
```

普通に動いてしまう．危険．
```
$ java -jar $x --config kgenprog.toml
...
testTimeLimit = PT10S
requiredSolutionsCount = 1
logLevel = DEBUG   ← ★ デフォルト値で解決されるっぽい
```

**Comment by hnymA** [comment]
- [ ] srcとtestが重複しているケース
- [ ] toml内で行末に余計なスペースがあるケース
- [ ] 型が正しくないケース
- [ ] 正数を期待するパラメタに負数や小数点を与えるケース
- [ ] 特定の文字列を期待するパラメタに期待外の文字列を与えるケース

**Comment by hnymA** [comment]
### 型が正しくないケース
正確にはUsageが出力された後にエラーが出力される．

> withTypeError.toml
```toml
root-dir = "./"
src = ["src/"]
test = ["test/"]
max-generation = "50" # type error here
```

> 出力結果
```
--config <path>                    : Specifies the path to the config file.
--crossover-first-variant [Elite | : Specifies first variant selection
 Random]                             strategy for crossover.

...

java.lang.IllegalArgumentException: Can not set int field jp.kusumotolab.kgenprog.Configuration$Builder.maxGeneration to java.lang.String

	at jp.kusumotolab.kgenprog.Configuration$Builder.buildFromCmdLineArgs(Configuration.java:376)
	at jp.kusumotolab.kgenprog.ConfigurationBuilderTest.testBuildFromConfigFileWithTypeError(ConfigurationBuilderTest.java:2848)
	...
	at java.lang.Thread.run(Thread.java:748)
```

printUsageした後に例外をthrowしているから？

https://github.com/kusumotolab/kGenProg/blob/e8c51439b525cf57e65870b0f0d280d7ef547cb0/src/main/java/jp/kusumotolab/kgenprog/Configuration.java#L372-L377
