### ISSUE TITLE
最初からテストに通ったときのエラーが不適切

### ISSUE THREAD

**Issue by mtj0928** [kusumotolab/kGenProg#472]
実行する時点でテストに通っていたものを実行したときのエラーが以下．

```
java.lang.IllegalArgumentException: candidateList must have at least one element.

	at jp.kusumotolab.kgenprog.ga.Roulette.<init>(Roulette.java:21)
	at jp.kusumotolab.kgenprog.ga.mutation.RandomMutation.exec(RandomMutation.java:43)
	at jp.kusumotolab.kgenprog.KGenProgMain.run(KGenProgMain.java:80)
	at jp.kusumotolab.kgenprog.KGenProgMainTest.testCloseToZero01(KGenProgMainTest.java:91)
```

ルーレットでエラーがて出るのは気持ち悪い．
どこでどんなエラーを出力するべきか，そもそもエラーなのかは要検討．
優先度は高くないです．

**Comment by a-tanikd** [comment]
【2019/01/07 議論結果】
- 初期テストを切り出す
- 別 issue に切り出して対処する
  - 別 issue のタイトルが決めにくいので pending

**Comment by shinsuke-mat** [comment]
#802 で解決
