### ISSUE TITLE
VariantStoreSerializerTest.testConfigurationSerialization が FAIL する

### ISSUE THREAD

**Issue by h-matsuo** [kusumotolab/kGenProg#549]
Related to #512.

カバレッジの計測のため `build.gradle` に `jacoco` プラグインを追加したところ，テストが FAIL するようになった．

## 変更箇所

```diff
diff --git a/build.gradle b/build.gradle
index 04f768cb..98c6c46a 100644
--- a/build.gradle
+++ b/build.gradle
@@ -13,6 +13,9 @@ apply plugin: 'java'
 apply plugin: 'eclipse'
 apply plugin: 'idea'

+// Apply JaCoCo plugin
+apply plugin: 'jacoco'
+
 // Set compiler version
 sourceCompatibility = '1.8'
 targetCompatibility = '1.8'
```

## FAIL したテストの出力

```
java.lang.AssertionError: 
Expecting:
  <["targetProject",
    "executionTests",
    "outDir",
    "mutationGeneratingCount",
    "crossoverGeneratingCount",
    "headcount",
    "maxGeneration",
    "timeLimit",
    "testTimeLimit",
    "requiredSolutionsCount",
    "logLevel",
    "randomSeed",
    "scope",
    "needNotOutput"]>
to contain only:
  <["targetProject",
    "executionTests",
    "outDir",
    "mutationGeneratingCount",
    "crossoverGeneratingCount",
    "headcount",
    "maxGeneration",
    "timeLimit",
    "testTimeLimit",
    "requiredSolutionsCount",
    "logLevel",
    "randomSeed",
    "scope",
    "needNotOutput",
    "$jacocoData"]>
but could not find the following elements:
  <["$jacocoData"]>

	at jp.kusumotolab.kgenprog.output.VariantStoreSerializerTest.testConfigurationSerialization(VariantStoreSerializerTest.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:303)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:297)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by shinsuke-mat** [comment]
jacocoはコンパイル時にフィールド `$jacocoData` を加えるので，
下手にリフレクションを使うと死ぬ．

ここでfilterを足せば良い．
https://github.com/kusumotolab/kGenProg/blob/061ffe6a352e5cb06627fecbccb9b213c3ba9e88/src/test/java/jp/kusumotolab/kgenprog/output/VariantStoreSerializerTest.java#L143-L147
