### ISSUE TITLE
win環境でgradle testが落ちる

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg#613]
VariantSerializerTestが悪いっぽい

```bash
$ gradle test
Starting a Gradle Daemon, 1 busy Daemon could not be reused, use --status for details
...

jp.kusumotolab.kgenprog.output.VariantSerializerTest > testVariant FAILED
    java.lang.AssertionError at VariantSerializerTest.java:112

```

junitレポート
```
java.lang.AssertionError: 
Expecting empty but was:<[{"fileName":"example.CloseToZero","diff":"--- example.CloseToZero\r\n+++ example.CloseToZero\r\n@@ -3,13 +3,13 @@\r\n public class CloseToZero {\r\n \r\n   /**\r\n-   * 整数をゼロに一つ近づけるメソッド\r\n+   * 謨ｴ謨ｰ繧偵ぞ繝ｭ縺ｫ荳�縺､霑代▼縺代ｋ繝｡繧ｽ繝�繝�\r\n    * \r\n-   * bug: 0を与えたときに0であるべきが1になる\r\n+   * bug: 0繧剃ｸ弱∴縺溘→縺阪↓0縺ｧ縺ゅｋ縺ｹ縺阪′1縺ｫ縺ｪ繧�\r\n    * \r\n-   * fix1: バグ行を削除<br>\r\n-   * fix2: バグ行の次に 'n--;' を追加<br>\r\n-   * fix3: バグ行を 'return n;' で置換\r\n+   * fix1: 繝舌げ陦後ｒ蜑企勁<br>\r\n+   * fix2: 繝舌げ陦後�ｮ谺｡縺ｫ 'n--;' 繧定ｿｽ蜉�<br>\r\n+   * fix3: 繝舌げ陦後ｒ 'return n;' 縺ｧ鄂ｮ謠�\r\n    * \r\n    * @param n\r\n    * @return"}]>
	at jp.kusumotolab.kgenprog.output.VariantSerializerTest.testVariant(VariantSerializerTest.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:303)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:297)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

おそらく実装のこの部分
```java
    final JsonArray serializedPatches = serializedVariant.get(JsonKeyAlias.Variant.PATCH)
        .getAsJsonArray();
    assertThat(serializedPatches).isEmpty();
```

**Comment by shinsuke-mat** [comment]
あと細かいリクエスト

この部分とても読みにくい．
工夫できない？
少なくとも「jsonの値の取り出しブロック」と「assertブロック」をまとめたほうがよさそう．

https://github.com/kusumotolab/kGenProg/blob/495a6ae4f3bcad566cf2b41e7078fa54faac5cff/src/test/java/jp/kusumotolab/kgenprog/output/VariantSerializerTest.java#L90-L118

**Comment by ty-v1** [comment]
windowsからgradleを実行すると，SJISでJavaが動くため，期待しないdiff(patch)が生成されるため

**Comment by ty-v1** [comment]
#389 に依存
