### ISSUE TITLE
Can kGenprog repair bugs from Defects4J benchmark ?

### ISSUE THREAD

**Issue by DehengYang** [kusumotolab/kGenProg#641]
Sorry for interrupting you with this question.

The current kGenprog is written under JDK 1.8. For Defects4J, as I know, mainly supports JDK 1.7. And some Defects4J bugs may fail when tested in JDK 1.8.

So I would like to ask that how kGenprog overcomes the difference of JDK versions which may bring extra failed test cases, and how many Defects4J bugs can be repaired by kGenprog now.

Thank you!

**Comment by shinsuke-mat** [comment]
Hi DehengYang.
Thank you for interesting us.

> Can kGenprog repair bugs from Defects4J benchmark?

The answer is YES.
Our tool can repair some bugs from (a part of) d4j dataset.

First of all, our development is currently ongoing.
Complete evaluation using all d4j dataset has not done yet.
We're trying to evaluate using only 106 bugs of Apache Math project included in d4j.

But, as you pointed out, some Math bugs cannot be tested due to the difference of JDK version.
The following is an examples of Math001 using JDK1.7.

```bash
math001$ java -version
java version "1.7.0_221"
OpenJDK Runtime Environment (IcedTea 2.6.18) (7u221-2.6.18-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.221-b02, mixed mode)

math001$ mvn clean test
...
Tests in error:
  FractionTest.testDigitLimitConstructor:134 » FractionConversion illegal state:...
  BigFractionTest.testDigitLimitConstructor:159 » FractionConversion illegal sta...

Tests run: 5246, Failures: 0, Errors: 2, Skipped: 51
...
```

It's ok, but on JDK1.8,

```bash
math001$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-2~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

math001$ mvn clean test
...
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
FATAL ERROR in native method: processing of -javaagent failed
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.
        at org.jacoco.agent.rt.internal_5d10cad.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:138)
        at org.jacoco.agent.rt.internal_5d10cad.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:99)
        at org.jacoco.agent.rt.internal_5d10cad.PreMain.createRuntime(PreMain.java:51)
        at org.jacoco.agent.rt.internal_5d10cad.PreMain.premain(PreMain.java:43)
        ... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
        at java.lang.Class.getField(Class.java:1703)
        at org.jacoco.agent.rt.internal_5d10cad.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:136)
        ... 9 more
Aborted (core dumped)

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
...
```

Build was succeeded but JUnit test won't run because of jacoco which is a code coverage tool.
This problem might due to a maven surefire bug.
https://issues.apache.org/jira/browse/SUREFIRE-1588
(i don't understand the detailed reason)

It means Math001 can be built using JDK1.8,
but the problem occures when JUnit test is executed using maven on JDK1.8 environment.

In contrast to that, our tool don't depend on maven.
Build and test are conducted on our way.
So, i mean, all Math's 106 bugs can be built and tested on our tool without extra effort.

Regards

**Comment by DehengYang** [comment]
Thank you for your prompt reply! 

So that means, you are creating your own ways to run D4J Math bugs in JDK 1.8, instead of relying on Maven. 

That's pretty cool. Thank you for your detailed answer!

**Comment by jose** [comment]
Quick question, why would you run `mvn test` on a D4J's bug instead of `defects4j test` ?
