### ISSUE TITLE
パッチエンコーディングの環境依存問題が残っている

### ISSUE THREAD

**Issue by shinsuke-mat** [kusumotolab/kGenProg#803]
see #798

パッチのテスト `PatchSerializerTest.java#testPatch` が環境によって落ちる．
間違いなくエンコーディング周りの問題．

**Comment by shinsuke-mat** [comment]
win desktop
```
java.lang.AssertionError: 
Expected size:<1> but was:<0> in:
<[]>

	at jp.kusumotolab.kgenprog.output.PatchSerializerTest.testPatch(PatchSerializerTest.java:110)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:303)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:297)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by shinsuke-mat** [comment]
win notebook, idea, non gradle
```
pass
```

win notebook, idea, gradle
```

Expected size:<1> but was:<2> in:
<[{"fileName":"example.CloseToZero","diff":"--- example.CloseToZero\r\n+++ example.CloseToZero\r\n@@ -3,13 +3,13 @@\r\n public class CloseToZero {\r\n \r\n   /**\r\n-   * 謨ｴ謨ｰ繧偵ぞ繝ｭ縺ｫ荳�縺､霑代▼縺代ｋ繝｡繧ｽ繝�繝�\r\n+   * 隰ｨ�ｽｴ隰ｨ�ｽｰ郢ｧ蛛ｵ縺樒ｹ晢ｽｭ邵ｺ�ｽｫ闕ｳ�ｿｽ邵ｺ�ｽ､髴台ｻ｣笆ｼ邵ｺ莉｣�ｽ狗ｹ晢ｽ｡郢ｧ�ｽｽ郢晢ｿｽ郢晢ｿｽ\r\n    * \r\n-   * bug: 0繧剃ｸ弱∴縺溘→縺阪↓0縺ｧ縺ゅｋ縺ｹ縺阪′1縺ｫ縺ｪ繧�\r\n+   * bug: 0郢ｧ蜑�ｽｸ蠑ｱ竏ｴ邵ｺ貅倪�堤ｸｺ髦ｪ竊�0邵ｺ�ｽｧ邵ｺ繧��ｽ狗ｸｺ�ｽｹ邵ｺ髦ｪ窶ｲ1邵ｺ�ｽｫ邵ｺ�ｽｪ郢ｧ�ｿｽ\r\n    * \r\n-   * fix1: 繝舌げ陦後ｒ蜑企勁<br>\r\n-   * fix2: 繝舌げ陦後�ｮ谺｡縺ｫ 'n--;' 繧定ｿｽ蜉�<br>\r\n-   * fix3: 繝舌げ陦後ｒ 'return n;' 縺ｧ鄂ｮ謠�\r\n+   * fix1: 郢晁�後￡髯ｦ蠕鯉ｽ定恆莨∝求<br>\r\n+   * fix2: 郢晁�後￡髯ｦ蠕鯉ｿｽ�ｽｮ隹ｺ�ｽ｡邵ｺ�ｽｫ 'n--;' 郢ｧ螳夲ｽｿ�ｽｽ陷会ｿｽ<br>\r\n+   * fix3: 郢晁�後￡髯ｦ蠕鯉ｽ� 'return n;' 邵ｺ�ｽｧ驗ゑｽｮ隰��ｿｽ\r\n    * \r\n    * @param n\r\n    * @return"},{"fileName":"example.CloseToZero","diff":"--- example.CloseToZero\r\n+++ example.CloseToZero\r\n@@ -3,13 +3,13 @@\r\n public class CloseToZero {\r\n \r\n   /**\r\n-   * 整数をゼロに一つ近づけるメソッド\r\n+   * 謨ｴ謨ｰ繧偵ぞ繝ｭ縺ｫ荳�縺､霑代▼縺代ｋ繝｡繧ｽ繝�繝�\r\n    * \r\n-   * bug: 0を与えたときに0であるべきが1になる\r\n+   * bug: 0繧剃ｸ弱∴縺溘→縺阪↓0縺ｧ縺ゅｋ縺ｹ縺阪′1縺ｫ縺ｪ繧�\r\n    * \r\n-   * fix1: バグ行を削除<br>\r\n-   * fix2: バグ行の次に 'n--;' を追加<br>\r\n-   * fix3: バグ行を 'return n;' で置換\r\n+   * fix1: 繝舌げ陦後ｒ蜑企勁<br>\r\n+   * fix2: 繝舌げ陦後�ｮ谺｡縺ｫ 'n--;' 繧定ｿｽ蜉�<br>\r\n+   * fix3: 繝舌げ陦後ｒ 'return n;' 縺ｧ鄂ｮ謠�\r\n    * \r\n    * @param n\r\n    * @return\r\n@@ -22,6 +22,7 @@\r\n     } else {\r\n       n++;\r\n     }\r\n+\tjson();\r\n     return n;\r\n   }\r\n }"}]>
java.lang.AssertionError: 
Expected size:<1> but was:<2> in:
<[{"fileName":"example.CloseToZero","diff":"--- example.CloseToZero\r\n+++ example.CloseToZero\r\n@@ -3,13 +3,13 @@\r\n public class CloseToZero {\r\n \r\n   /**\r\n-   * 謨ｴ謨ｰ繧偵ぞ繝ｭ縺ｫ荳�縺､霑代▼縺代ｋ繝｡繧ｽ繝�繝�\r\n+   * 隰ｨ�ｽｴ隰ｨ�ｽｰ郢ｧ蛛ｵ縺樒ｹ晢ｽｭ邵ｺ�ｽｫ闕ｳ�ｿｽ邵ｺ�ｽ､髴台ｻ｣笆ｼ邵ｺ莉｣�ｽ狗ｹ晢ｽ｡郢ｧ�ｽｽ郢晢ｿｽ郢晢ｿｽ\r\n    * \r\n-   * bug: 0繧剃ｸ弱∴縺溘→縺阪↓0縺ｧ縺ゅｋ縺ｹ縺阪′1縺ｫ縺ｪ繧�\r\n+   * bug: 0郢ｧ蜑�ｽｸ蠑ｱ竏ｴ邵ｺ貅倪�堤ｸｺ髦ｪ竊�0邵ｺ�ｽｧ邵ｺ繧��ｽ狗ｸｺ�ｽｹ邵ｺ髦ｪ窶ｲ1邵ｺ�ｽｫ邵ｺ�ｽｪ郢ｧ�ｿｽ\r\n    * \r\n-   * fix1: 繝舌げ陦後ｒ蜑企勁<br>\r\n-   * fix2: 繝舌げ陦後�ｮ谺｡縺ｫ 'n--;' 繧定ｿｽ蜉�<br>\r\n-   * fix3: 繝舌げ陦後ｒ 'return n;' 縺ｧ鄂ｮ謠�\r\n+   * fix1: 郢晁�後￡髯ｦ蠕鯉ｽ定恆莨∝求<br>\r\n+   * fix2: 郢晁�後￡髯ｦ蠕鯉ｿｽ�ｽｮ隹ｺ�ｽ｡邵ｺ�ｽｫ 'n--;' 郢ｧ螳夲ｽｿ�ｽｽ陷会ｿｽ<br>\r\n+   * fix3: 郢晁�後￡髯ｦ蠕鯉ｽ� 'return n;' 邵ｺ�ｽｧ驗ゑｽｮ隰��ｿｽ\r\n    * \r\n    * @param n\r\n    * @return"},{"fileName":"example.CloseToZero","diff":"--- example.CloseToZero\r\n+++ example.CloseToZero\r\n@@ -3,13 +3,13 @@\r\n public class CloseToZero {\r\n \r\n   /**\r\n-   * 整数をゼロに一つ近づけるメソッド\r\n+   * 謨ｴ謨ｰ繧偵ぞ繝ｭ縺ｫ荳�縺､霑代▼縺代ｋ繝｡繧ｽ繝�繝�\r\n    * \r\n-   * bug: 0を与えたときに0であるべきが1になる\r\n+   * bug: 0繧剃ｸ弱∴縺溘→縺阪↓0縺ｧ縺ゅｋ縺ｹ縺阪′1縺ｫ縺ｪ繧�\r\n    * \r\n-   * fix1: バグ行を削除<br>\r\n-   * fix2: バグ行の次に 'n--;' を追加<br>\r\n-   * fix3: バグ行を 'return n;' で置換\r\n+   * fix1: 繝舌げ陦後ｒ蜑企勁<br>\r\n+   * fix2: 繝舌げ陦後�ｮ谺｡縺ｫ 'n--;' 繧定ｿｽ蜉�<br>\r\n+   * fix3: 繝舌げ陦後ｒ 'return n;' 縺ｧ鄂ｮ謠�\r\n    * \r\n    * @param n\r\n    * @return\r\n@@ -22,6 +22,7 @@\r\n     } else {\r\n       n++;\r\n     }\r\n+\tjson();\r\n     return n;\r\n   }\r\n }"}]>
	at jp.kusumotolab.kgenprog.output.PatchSerializerTest.testPatch(PatchSerializerTest.java:110)
	at
```

**Comment by ty-v1** [comment]
@ty-v1 の環境では，idea，idea + gradleの両方の環境でpassした

**Comment by shinsuke-mat** [comment]
すまん．たぶんこっちの環境依存の問題でした．

notebook → git-pull 忘れ．1.7.3 で実行していた．落ちるのは当然．
desktop → 理由は不明．若干不安はあるが現在はmasterでも通ることを確認．
